name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or the version your project uses

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (Non-Functional Test)
        run: npm run lint # Ensure you have ESLint set up in your package.json

      - name: Run Functional Tests
        run: npm test # Ensure you have your tests defined in package.json
